[package]
name = "standalone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ui = {path = "../ui"}
eframe = "0.20.1"
tokio = {version = "1.23.1", default-features = false, features = ["macros"]}
