[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc = { path = "../rpc", default-features = false, features = ["server"] }
tarpc = { git = "https://github.com/whizsid/tarpc.git", branch = "wasm-support", default-features = false, features = ["server"] }
async-trait = "^0.1"
