[package]
name = "ui"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20.1"
rfd = "0.10.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
poll-promise = {version = "0.2.0", default-features = false, features = ["web"]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
poll-promise = {version = "0.2.0", default-features = false, features = ["tokio"]}

[features]
# Opening remote projects
open_remote = []
# Opening local files
open_local = []
